name: Deploy Example

on:
  push:
    branchs: ["main"] # Only run on main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools
      
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Publish .NET
        run: dotnet publish BlazorDeploy.csproj -c Release -o docs --no-logo
      
      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      - name: Upload Project to Github Pages
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4